### ISSUE TITLE
Get sensible values as Environment Variables

### ISSUE THREAD

**Issue by falcaoaugustos** [Beakyn/gha-close-milestone#1]
### Current Scenario

```
- name: Close Milestone
  uses: Beakyn/close-milestone@master
  with:
    github-token: ${{ github.token }}
    repository: ${{ github.repository }}
    milestone: ${{ github.event.inputs.milestone }}
```

### Describe the solution you'd like

```
- name: Close Milestone
  uses: Beakyn/close-milestone@master
  env:
    GITHUB_TOKEN: ${{ github.token }}
  with:
    repository: ${{ github.repository }}
    milestone: ${{ github.event.inputs.milestone }}
```
